New loginpage
rCatMAN/CatMusic pull request #5
Opened 2023-01-25 07:15 UTC by rCatMAN

2023-01-25 09:24 UTC, oil-oil requested changes
提交代码前记得先 `yarn lint:fix`

2023-01-25 09:24 UTC, oil-oil commented on vue.d.ts
> +export default Component }
文件末尾缺了换行

2023-01-25 09:24 UTC, oil-oil commented on index.html
> +    <link rel="icon" type="image/svg+xml" href="/src//icons/svg/back.svg" />
这里为啥要用这个图标

2023-01-25 09:24 UTC, oil-oil commented on src/components/header/index.vue
> +<script setup lang='ts'>
将 `script` 移到 `html` 后面

2023-01-25 09:24 UTC, oil-oil commented on index.html
> +    <link rel="icon" type="image/svg+xml" href="/src//icons/svg/back.svg" />
这里为啥要用这个图标

2023-01-25 09:24 UTC, oil-oil commented on src/components/header/index.vue
> +<script setup lang='ts'>
将 `script` 移到 `html` 后面

2023-01-25 09:24 UTC, oil-oil commented on src/pages/home/index.vue
> +        <div class="main-Page bg-white mainPage">
这里为啥有两个重复的 main page，而且 class 要用横杠全小写的格式

2023-01-25 09:24 UTC, oil-oil commented on src/components/header/index.vue
> +const toPage = ()=>{
这种简单方法建议直接写在行内

2023-01-25 09:24 UTC, oil-oil commented on src/components/svg-icon/index.vue
> +export default defineComponent({
在 ts 项目中 `defineComponent` 定义组件参数可以使用方法泛型，而不是传递参数，具体可以看文档 https://cn.vuejs.org/guide/typescript/composition-api.html

2023-01-25 09:24 UTC, oil-oil commented on src/components/svg-icon/index.vue
> +  setup(props) {
使用 `setup` 语法糖，而不是使用 `setup` 方法

2023-01-25 09:24 UTC, oil-oil commented on src/pages/home/login/index.vue
> +    <SvgIcon @click="backPage" iconClass="back" class="iconColor text-black absolute cursor-pointer" style="left: 5%;top:5%;"/>
```suggestion
    <SvgIcon @click="backPage" iconClass="back" class="icon-color text-black absolute cursor-pointer" style="left: 5%;top:5%;"/>
```

2023-01-25 09:24 UTC, oil-oil commented on src/pages/home/login/index.vue
> +            <div class="titleText absolute font-black text-5xl w-full ml-8">
class 格式问题全局检查一下

2023-01-25 09:24 UTC, oil-oil commented on src/pages/home/login/index.vue
> +    <SvgIcon @click="backPage" iconClass="back" class="iconColor text-black absolute cursor-pointer" style="left: 5%;top:5%;"/>
```suggestion
    <SvgIcon @click="backPage" iconClass="back" class="icon-color text-black absolute cursor-pointer" style="left: 5%;top:5%;"/>
```

2023-01-25 09:53 UTC, rCatMAN commented on index.html
> +    <link rel="icon" type="image/svg+xml" href="/src//icons/svg/back.svg" />
只是测试一下这个地方直接用svg可不可以 之后再选个合适的logo放上去

2023-01-25 10:29 UTC, rCatMAN commented on src/components/svg-icon/index.vue
> +export default defineComponent({
已更换为方法泛型定义组件

2023-01-25 10:31 UTC, rCatMAN commented on src/components/svg-icon/index.vue
> +  setup(props) {
已使用

2023-01-25 10:46 UTC, rCatMAN reviewed
已修改

2023-01-25 12:25 UTC, oil-oil requested changes

2023-01-25 12:25 UTC, oil-oil commented on src/request/api.ts
> +export const PhoneLoginApi = (password: number | undefined, phone: string | undefined) => instance.post(`/login/cellphone?password=${password}&phone=${phone}`)
```suggestion
export const phoneLoginApi = (password: number, phone: string) => instance.post(`/login/cellphone?password=${password}&phone=${phone}`)

```
post 请求应该直接在 data 字段里传递参数，而不是拼接url

2023-01-25 12:25 UTC, oil-oil commented on src/request/api.ts
> +export const LoginStatusApi = () => instance.get("/login/status")
```suggestion
export const loginStatusApi = () => instance.get("/login/status")
```

2023-01-27 01:33 UTC, oil-oil commented on src/pages/home/login/index.vue
> +                <div @click="Login()" class="login-button flex items-center justify-center cursor-pointer mt-16"
```suggestion
                <div @click="Login" class="flex items-center justify-center cursor-pointer mt-16 login-button"
```
如果没有传递参数，这里不需要写小括号，自定义的 class 建议放在最后，避免被其他样式覆盖

2023-01-27 01:33 UTC, oil-oil commented on src/request/request.ts
> +        //php 的 post 传输请求头一定要这个 不然报错 接收不到值
没有什么用的注释可以去掉

2023-01-27 01:33 UTC, oil-oil commented on src/pages/home/login/index.vue
> +const Login = () => {
```suggestion
const login = () => {
```

2023-01-27 01:34 UTC, oil-oil requested changes

2023-01-27 01:34 UTC, oil-oil commented on src/request/type.ts
> +// 返回res.data的interface
```suggestion
```

2023-01-27 10:17 UTC, oil-oil approved these changes

2023-01-27 10:17 UTC, merged