feat: add login and logout function
rCatMAN/CatMusic pull request #7
Opened 2023-02-01 22:00 UTC by rCatMAN

2023-02-02 04:19 UTC, oil-oil requested changes
提交代码前先合并主分支，再跑一下 lint

2023-02-02 04:19 UTC, oil-oil commented on src/pages/home/login/index.vue
> +const switchLoginMde = () => {
```suggestion
const switchLoginMode = () => {
```

2023-02-02 04:19 UTC, oil-oil commented on src/pages/home/login/index.vue
> +    }
```suggestion
    loginMode.value = loginMode.value === LoginMode.QrCode? LoginMode.PhoneAndPassword: LoginMode.QrCode
```

2023-02-02 04:19 UTC, oil-oil commented on src/request/api/user.ts
> +export const qrcodeCreateApi = (qrkey: string) =>
每个 export 间加个空行

2023-02-02 04:19 UTC, oil-oil commented on src/components/qrcode/QrcodeLogin.vue
> +        console.log(1, keyRes)
提交代码时，建议把没用的 console.log 全部删除

2023-02-02 04:19 UTC, oil-oil commented on src/components/qrcode/QrcodeLogin.vue
> +let intervalId: any
```suggestion
let intervalId: number
```

2023-02-02 04:19 UTC, oil-oil commented on src/components/qrcode/QrcodeLogin.vue
> +})
```suggestion
onUnmounted(() => {
   if(intervalId){
    clearInterval(intervalId)
   }
})
```

2023-02-02 07:22 UTC, rCatMAN commented on src/components/qrcode/QrcodeLogin.vue
> +let intervalId: any
这里改number类型后 会报不能将setInterval函数返回的id值类型为Timer分配给number的错误

2023-02-02 13:01 UTC, oil-oil commented on src/pages/home/login/index.vue
> +    // }
delete

2023-02-06 11:01 UTC, oil-oil approved these changes

2023-02-06 12:27 UTC, merged